// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// //import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDLnaep1YfUlmvkcVya3OhiIJFeDpxrJcU',
//     appId: '1:1029320548066:android:97eef714503f14b0b708bb',
//     messagingSenderId: '1029320548066',
//     projectId: 'datingapp-5029b',
//     storageBucket: 'datingapp-5029b.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBtdUAI7piJ8tm-Guhb_t50_K_qo2DhwuI',
//     appId: '1:1029320548066:ios:dc200be8facf64afb708bb',
//     messagingSenderId: '1029320548066',
//     projectId: 'datingapp-5029b',
//     storageBucket: 'datingapp-5029b.appspot.com',
//     iosBundleId: 'com.example.datingapp',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyBBGAX9tT16qbJigQ1fCjgyElTWFK3gFDo',
//     appId: '1:1029320548066:web:e97cfeb8196515d5b708bb',
//     messagingSenderId: '1029320548066',
//     projectId: 'datingapp-5029b',
//     authDomain: 'datingapp-5029b.firebaseapp.com',
//     storageBucket: 'datingapp-5029b.appspot.com',
//     measurementId: 'G-VN9T2NEJZR',
//   );
// }
